/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mvc.controller.VehiculoController;
import mvc.model.Vehiculo;

import java.awt.Color;
import java.awt.Frame;

import com.formdev.flatlaf.intellijthemes.FlatOneDarkIJTheme;

/**
 *
 * @author Rodmat95
 */
public class Menu extends javax.swing.JFrame {

    int xMouse, yMouse;
    private boolean maximized = false;
    
    private VehiculoController vehiculoController = new VehiculoController();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        
        llenarTabla();    
        
        tblVehiculo.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                tblVehiculoMouseClicked(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBody = new javax.swing.JPanel();
        pnlBarraTitle = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlMinimizar = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JButton();
        pnlMaximizar = new javax.swing.JPanel();
        btnMaximizar = new javax.swing.JButton();
        pnlCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbxID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbxPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tbxMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tbxModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tbxAño = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tbxColor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        pnlAgregar = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        pnlModificar = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        pnlEliminar = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        pnlNuevo = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setFont(new java.awt.Font("Microsoft YaHei", 0, 15)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(470, 574));
        setMinimumSize(new java.awt.Dimension(470, 574));
        setUndecorated(true);
        setSize(new java.awt.Dimension(470, 574));

        pnlBody.setBackground(new java.awt.Color(204, 204, 204));
        pnlBody.setForeground(new java.awt.Color(0, 0, 0));
        pnlBody.setAlignmentX(0.0F);
        pnlBody.setAlignmentY(0.0F);
        pnlBody.setMaximumSize(new java.awt.Dimension(470, 574));
        pnlBody.setMinimumSize(new java.awt.Dimension(470, 574));
        pnlBody.setName(""); // NOI18N
        pnlBody.setPreferredSize(new java.awt.Dimension(470, 574));

        pnlBarraTitle.setBackground(new java.awt.Color(0, 0, 0));
        pnlBarraTitle.setForeground(new java.awt.Color(255, 255, 255));
        pnlBarraTitle.setAlignmentX(0.0F);
        pnlBarraTitle.setAlignmentY(0.0F);
        pnlBarraTitle.setMaximumSize(new java.awt.Dimension(470, 34));
        pnlBarraTitle.setMinimumSize(new java.awt.Dimension(470, 34));
        pnlBarraTitle.setName("Barra de Titulo"); // NOI18N
        pnlBarraTitle.setPreferredSize(new java.awt.Dimension(470, 34));
        pnlBarraTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlBarraTitleMouseDragged(evt);
            }
        });
        pnlBarraTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBarraTitleMousePressed(evt);
            }
        });

        lblTitulo.setBackground(new java.awt.Color(31, 31, 31));
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Vehiculos");

        pnlMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        pnlMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        pnlMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMinimizar.setMinimumSize(new java.awt.Dimension(46, 32));

        btnMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimizar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setText("–");
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMinimizar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnMinimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setPreferredSize(new java.awt.Dimension(46, 32));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMinimizarLayout = new javax.swing.GroupLayout(pnlMinimizar);
        pnlMinimizar.setLayout(pnlMinimizarLayout);
        pnlMinimizarLayout.setHorizontalGroup(
            pnlMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMinimizarLayout.setVerticalGroup(
            pnlMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMaximizar.setBackground(new java.awt.Color(0, 0, 0));
        pnlMaximizar.setForeground(new java.awt.Color(255, 255, 255));
        pnlMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMaximizar.setEnabled(false);
        pnlMaximizar.setMinimumSize(new java.awt.Dimension(46, 32));

        btnMaximizar.setBackground(new java.awt.Color(31, 31, 31));
        btnMaximizar.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btnMaximizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMaximizar.setText("⬛");
        btnMaximizar.setBorder(null);
        btnMaximizar.setBorderPainted(false);
        btnMaximizar.setContentAreaFilled(false);
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMaximizar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnMaximizar.setEnabled(false);
        btnMaximizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaximizar.setPreferredSize(new java.awt.Dimension(46, 32));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMaximizarLayout = new javax.swing.GroupLayout(pnlMaximizar);
        pnlMaximizar.setLayout(pnlMaximizarLayout);
        pnlMaximizarLayout.setHorizontalGroup(
            pnlMaximizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMaximizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMaximizarLayout.setVerticalGroup(
            pnlMaximizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMaximizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlCerrar.setBackground(new java.awt.Color(0, 0, 0));
        pnlCerrar.setForeground(new java.awt.Color(255, 255, 255));
        pnlCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlCerrar.setMinimumSize(new java.awt.Dimension(46, 32));

        btnCerrar.setBackground(new java.awt.Color(31, 31, 31));
        btnCerrar.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("⨉");
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setPreferredSize(new java.awt.Dimension(46, 32));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlCerrarLayout = new javax.swing.GroupLayout(pnlCerrar);
        pnlCerrar.setLayout(pnlCerrarLayout);
        pnlCerrarLayout.setHorizontalGroup(
            pnlCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCerrarLayout.setVerticalGroup(
            pnlCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarLayout.createSequentialGroup()
                .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBarraTitleLayout = new javax.swing.GroupLayout(pnlBarraTitle);
        pnlBarraTitle.setLayout(pnlBarraTitleLayout);
        pnlBarraTitleLayout.setHorizontalGroup(
            pnlBarraTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraTitleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        pnlBarraTitleLayout.setVerticalGroup(
            pnlBarraTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraTitleLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(pnlBarraTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        jPanel1.setBackground(new java.awt.Color(193, 199, 215));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(470, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(470, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 540));

        jPanel2.setBackground(new java.awt.Color(193, 199, 215));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(33, 36, 43));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMaximumSize(new java.awt.Dimension(450, 230));
        jPanel2.setMinimumSize(new java.awt.Dimension(450, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 230));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 36, 43));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ID");

        tbxID.setEditable(false);
        tbxID.setBackground(new java.awt.Color(33, 36, 43));
        tbxID.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tbxID.setForeground(new java.awt.Color(159, 162, 171));
        tbxID.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 36, 43));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Placa");

        tbxPlaca.setBackground(new java.awt.Color(33, 36, 43));
        tbxPlaca.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tbxPlaca.setForeground(new java.awt.Color(159, 162, 171));
        tbxPlaca.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 36, 43));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Marca");

        tbxMarca.setBackground(new java.awt.Color(33, 36, 43));
        tbxMarca.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tbxMarca.setForeground(new java.awt.Color(159, 162, 171));
        tbxMarca.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 36, 43));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Modelo");

        tbxModelo.setBackground(new java.awt.Color(33, 36, 43));
        tbxModelo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tbxModelo.setForeground(new java.awt.Color(159, 162, 171));
        tbxModelo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 36, 43));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Año");

        tbxAño.setBackground(new java.awt.Color(33, 36, 43));
        tbxAño.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tbxAño.setForeground(new java.awt.Color(159, 162, 171));
        tbxAño.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 36, 43));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Color");

        tbxColor.setBackground(new java.awt.Color(33, 36, 43));
        tbxColor.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tbxColor.setForeground(new java.awt.Color(159, 162, 171));
        tbxColor.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbxID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(194, 194, 194))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel3.setBackground(new java.awt.Color(193, 199, 215));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setMaximumSize(new java.awt.Dimension(450, 50));
        jPanel3.setMinimumSize(new java.awt.Dimension(450, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 50));

        pnlAgregar.setBackground(new java.awt.Color(33, 36, 43));
        pnlAgregar.setForeground(new java.awt.Color(255, 255, 255));
        pnlAgregar.setAlignmentX(0.0F);
        pnlAgregar.setAlignmentY(0.0F);
        pnlAgregar.setMaximumSize(new java.awt.Dimension(100, 30));
        pnlAgregar.setMinimumSize(new java.awt.Dimension(100, 30));
        pnlAgregar.setPreferredSize(new java.awt.Dimension(100, 30));

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(159, 162, 171));
        btnAgregar.setText("Agregar");
        btnAgregar.setAlignmentY(0.0F);
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarLayout = new javax.swing.GroupLayout(pnlAgregar);
        pnlAgregar.setLayout(pnlAgregarLayout);
        pnlAgregarLayout.setHorizontalGroup(
            pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAgregarLayout.setVerticalGroup(
            pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlModificar.setBackground(new java.awt.Color(33, 36, 43));
        pnlModificar.setForeground(new java.awt.Color(255, 255, 255));
        pnlModificar.setAlignmentX(0.0F);
        pnlModificar.setAlignmentY(0.0F);
        pnlModificar.setMaximumSize(new java.awt.Dimension(100, 30));
        pnlModificar.setMinimumSize(new java.awt.Dimension(100, 30));

        btnModificar.setBackground(new java.awt.Color(0, 0, 0));
        btnModificar.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(159, 162, 171));
        btnModificar.setText("Modificar");
        btnModificar.setAlignmentY(0.0F);
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnModificar.setDisplayedMnemonicIndex(0);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModificarLayout = new javax.swing.GroupLayout(pnlModificar);
        pnlModificar.setLayout(pnlModificarLayout);
        pnlModificarLayout.setHorizontalGroup(
            pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlModificarLayout.setVerticalGroup(
            pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlEliminar.setBackground(new java.awt.Color(33, 36, 43));
        pnlEliminar.setForeground(new java.awt.Color(255, 255, 255));
        pnlEliminar.setAlignmentX(0.0F);
        pnlEliminar.setAlignmentY(0.0F);
        pnlEliminar.setMaximumSize(new java.awt.Dimension(100, 30));
        pnlEliminar.setMinimumSize(new java.awt.Dimension(100, 30));

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(159, 162, 171));
        btnEliminar.setText("Eliminar");
        btnEliminar.setAlignmentY(0.0F);
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnEliminar.setDisplayedMnemonicIndex(0);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEliminarLayout = new javax.swing.GroupLayout(pnlEliminar);
        pnlEliminar.setLayout(pnlEliminarLayout);
        pnlEliminarLayout.setHorizontalGroup(
            pnlEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlEliminarLayout.setVerticalGroup(
            pnlEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlNuevo.setBackground(new java.awt.Color(33, 36, 43));
        pnlNuevo.setForeground(new java.awt.Color(255, 255, 255));
        pnlNuevo.setAlignmentX(0.0F);
        pnlNuevo.setAlignmentY(0.0F);
        pnlNuevo.setMaximumSize(new java.awt.Dimension(100, 100));
        pnlNuevo.setMinimumSize(new java.awt.Dimension(100, 30));

        btnNuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(159, 162, 171));
        btnNuevo.setText("Nuevo");
        btnNuevo.setAlignmentY(0.0F);
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnNuevo.setDisplayedMnemonicIndex(0);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoMouseExited(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNuevoLayout = new javax.swing.GroupLayout(pnlNuevo);
        pnlNuevo.setLayout(pnlNuevoLayout);
        pnlNuevoLayout.setHorizontalGroup(
            pnlNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNuevoLayout.setVerticalGroup(
            pnlNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(193, 199, 215));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel8.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jPanel8.setMaximumSize(new java.awt.Dimension(450, 220));
        jPanel8.setMinimumSize(new java.awt.Dimension(450, 220));
        jPanel8.setPreferredSize(new java.awt.Dimension(450, 220));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);
        jScrollPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane1.setFont(new java.awt.Font("Microsoft YaHei", 0, 15)); // NOI18N
        jScrollPane1.setMaximumSize(new java.awt.Dimension(340, 200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(340, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(340, 200));

        tblVehiculo.setBackground(new java.awt.Color(193, 199, 215));
        tblVehiculo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        tblVehiculo.setForeground(new java.awt.Color(33, 36, 43));
        tblVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Placa", "Marca", "Modelo", "Año", "Color"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVehiculo.setAlignmentX(0.0F);
        tblVehiculo.setAlignmentY(0.0F);
        tblVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblVehiculo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tblVehiculo.setGridColor(new java.awt.Color(159, 162, 171));
        tblVehiculo.setMaximumSize(new java.awt.Dimension(430, 172));
        tblVehiculo.setMinimumSize(new java.awt.Dimension(430, 172));
        tblVehiculo.setPreferredSize(new java.awt.Dimension(430, 200));
        tblVehiculo.setRowHeight(25);
        tblVehiculo.setSelectionBackground(new java.awt.Color(44, 48, 57));
        tblVehiculo.setSelectionForeground(new java.awt.Color(159, 162, 171));
        tblVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehiculo);
        if (tblVehiculo.getColumnModel().getColumnCount() > 0) {
            tblVehiculo.getColumnModel().getColumn(0).setResizable(false);
            tblVehiculo.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblVehiculo.getColumnModel().getColumn(1).setResizable(false);
            tblVehiculo.getColumnModel().getColumn(1).setPreferredWidth(55);
            tblVehiculo.getColumnModel().getColumn(2).setResizable(false);
            tblVehiculo.getColumnModel().getColumn(3).setResizable(false);
            tblVehiculo.getColumnModel().getColumn(4).setResizable(false);
            tblVehiculo.getColumnModel().getColumn(4).setPreferredWidth(35);
            tblVehiculo.getColumnModel().getColumn(5).setResizable(false);
            tblVehiculo.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBarraTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(pnlBarraTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlBody.getAccessibleContext().setAccessibleName("435");
        pnlBody.getAccessibleContext().setAccessibleDescription("530");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarTabla() {
        List<Vehiculo> listaVehiculos = vehiculoController.listarVehiculos();

        DefaultTableModel model = (DefaultTableModel) tblVehiculo.getModel();
        model.setRowCount(0);

        for (Vehiculo vehiculo : listaVehiculos) {
            Object[] rowData = {
                vehiculo.getId(),
                vehiculo.getPlaca(),
                vehiculo.getMarca(),
                vehiculo.getModelo(),
                vehiculo.getAnio(),
                vehiculo.getColor()
            };
            model.addRow(rowData);
        }
    }   
    
    private void agregarNuevoVehiculo() {
        String placa = tbxPlaca.getText();
        String marca = tbxMarca.getText();
        String modelo = tbxModelo.getText();
        int anio = Integer.parseInt(tbxAño.getText());
        String color = tbxColor.getText();

        Vehiculo nuevoVehiculo = new Vehiculo();
        nuevoVehiculo.setPlaca(placa);
        nuevoVehiculo.setMarca(marca);
        nuevoVehiculo.setModelo(modelo);
        nuevoVehiculo.setAnio(anio);
        nuevoVehiculo.setColor(color);

        vehiculoController.agregarVehiculo(nuevoVehiculo);

        llenarTabla();
        JOptionPane.showMessageDialog(this, "Vehículo agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void modificarVehiculo() {
        String idStr = tbxID.getText();

        int id = Integer.parseInt(idStr);
        String placa = tbxPlaca.getText();
        String marca = tbxMarca.getText();
        String modelo = tbxModelo.getText();
        int anio = Integer.parseInt(tbxAño.getText());
        String color = tbxColor.getText();

        Vehiculo vehiculoModificado = new Vehiculo();
        vehiculoModificado.setId(id);
        vehiculoModificado.setPlaca(placa);
        vehiculoModificado.setMarca(marca);
        vehiculoModificado.setModelo(modelo);
        vehiculoModificado.setAnio(anio);
        vehiculoModificado.setColor(color);

        vehiculoController.modificarVehiculo(vehiculoModificado);

        llenarTabla();
        JOptionPane.showMessageDialog(this, "Vehículo modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void eliminarVehiculo() {
        String idStr = tbxID.getText();
        try {
            int id = Integer.parseInt(idStr);

            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este vehículo?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        
            if (confirmacion == JOptionPane.YES_OPTION) {
                vehiculoController.eliminarVehiculo(id);
                llenarTabla();
                JOptionPane.showMessageDialog(this, "Vehículo eliminado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }
    
    private void nuevoVehiculo() {
        tbxID.setText("");
        tbxPlaca.setText("");
        tbxMarca.setText("");
        tbxModelo.setText("");
        tbxAño.setText("");
        tbxColor.setText("");
    }
    
    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        pnlMinimizar.setBackground(new Color(62,62,62));
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        pnlMinimizar.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        if (maximized){
            setExtendedState(Frame.NORMAL);
            maximized = false;
        }else{
            setExtendedState(Frame.MAXIMIZED_BOTH);
            maximized = true;
        }
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void btnMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseEntered
        pnlMaximizar.setBackground(new Color(62,62,62));
    }//GEN-LAST:event_btnMaximizarMouseEntered

    private void btnMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseExited
        pnlMaximizar.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnMaximizarMouseExited

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        pnlCerrar.setBackground(Color.red);
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        pnlCerrar.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnCerrarMouseExited

    private void pnlBarraTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBarraTitleMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_pnlBarraTitleMouseDragged

    private void pnlBarraTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBarraTitleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlBarraTitleMousePressed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarNuevoVehiculo();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculoMouseClicked
        int selectedRow = tblVehiculo.getSelectedRow();
        if (selectedRow != -1) {
            // Obtén los datos de la fila seleccionada
            String id = tblVehiculo.getValueAt(selectedRow, 0).toString();
            String placa = tblVehiculo.getValueAt(selectedRow, 1).toString();
            String marca = tblVehiculo.getValueAt(selectedRow, 2).toString();
            String modelo = tblVehiculo.getValueAt(selectedRow, 3).toString();
            String anio = tblVehiculo.getValueAt(selectedRow, 4).toString();
            String color = tblVehiculo.getValueAt(selectedRow, 5).toString();

            // Muestra los datos en los JTextField correspondientes
            tbxID.setText(id);
            tbxPlaca.setText(placa);
            tbxMarca.setText(marca);
            tbxModelo.setText(modelo);
            tbxAño.setText(anio);
            tbxColor.setText(color);
        }
    }//GEN-LAST:event_tblVehiculoMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificarVehiculo();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarVehiculo();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevoVehiculo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        pnlAgregar.setBackground(new Color(44,48,57));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        pnlAgregar.setBackground(new Color(33,36,43));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        pnlModificar.setBackground(new Color(44,48,57));
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        pnlModificar.setBackground(new Color(33,36,43));
    }//GEN-LAST:event_btnModificarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        pnlEliminar.setBackground(new Color(44,48,57));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        pnlEliminar.setBackground(new Color(33,36,43));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseEntered
        pnlNuevo.setBackground(new Color(44,48,57));
    }//GEN-LAST:event_btnNuevoMouseEntered

    private void btnNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseExited
        pnlNuevo.setBackground(new Color(33,36,43));
    }//GEN-LAST:event_btnNuevoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            FlatOneDarkIJTheme.setup();
            //UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAgregar;
    private javax.swing.JPanel pnlBarraTitle;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlCerrar;
    private javax.swing.JPanel pnlEliminar;
    private javax.swing.JPanel pnlMaximizar;
    private javax.swing.JPanel pnlMinimizar;
    private javax.swing.JPanel pnlModificar;
    private javax.swing.JPanel pnlNuevo;
    private javax.swing.JTable tblVehiculo;
    private javax.swing.JTextField tbxAño;
    private javax.swing.JTextField tbxColor;
    private javax.swing.JTextField tbxID;
    private javax.swing.JTextField tbxMarca;
    private javax.swing.JTextField tbxModelo;
    private javax.swing.JTextField tbxPlaca;
    // End of variables declaration//GEN-END:variables
}
